#Noob Editors
#Posy you mother Editor
from colorama import init, Fore
init()
from random import choice, randint
print("   hacker jahanami 🖤")
print(Fore.MAGENTA+''' 
        ,     \    /      ,        
       / \    )\__/(     / \       
      /   \  (_\  /_)   /   \      
 ____/_____\__\@  @/___/_____\____ 
|             |\../|              |
|              \VV/               |
|               H 💜        |
|_________________________________|
 |    /\ /      \\       \ /\    | 
 |  /   V        ))       V   \  | 
 |/            //        '     \| 
               V                ''')
smg = print(f'\33[92m    Version 1.0.1')

print(Fore.RED+' Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')

cod = print(Fore.GREEN+' [0] Code Sazi')
bug = print(Fore.RED+' [1] Bug list')
xxx = print(Fore.CYAN+' [2] Link xxx or Site xxx list')
tur = print(Fore.YELLOW+' [3] Code Tor')
dark = print(Fore.RED+' [4] link DARK')
viurs = print(Fore.YELLOW+' [5] VIURS')
di = print(Fore.CYAN+' [6] D script')
bg = print(Fore.RED+' [7] domain list')
gu = print(Fore.WHITE+' [8] bug dark')
pig = print(Fore.MAGENTA+' [9]virus Instagram')
cod = tur = print(Fore.YELLOW+' [10] code channe ')
code = print(Fore.WHITE+' [11] Code group')
ty = print(Fore.MAGENTA+' [12] mkhzn tor')
mhk = print(Fore.CYAN+' [13] Link sex bug sadh')
cd = print(Fore.RED+' [14] code account  ')
sh = print(Fore.GREEN+' [15] Satan.s site')
gl =input(f'\33[92m Enter number: ')
if gl=='0':

    bu = input(Fore.BLUE+' Enter xxx: ')
    xx = input(Fore.YELLOW+' Enter Link dark: ')
    tor = input(Fore.RED+' Enter code tor: ')
    lok = input(Fore.CYAN+' Enter Numerical algorithm: ')
    di = input(Fore.YELLOW+' Enter D script: ')
    ip = input(Fore.RED+' Enter ip Link sex: ')
    sr = input(Fore.BLUE+' Enter sors damin: ')
    
    amir =(xx+'='+bu+'+'+tor+'*'+lok+'/'+di+'-'+ip+'('+sr)
    print(amir)
algoritm = ["/y//d/f/","/f//d/","/d//f/h/","/f//a/y/","/i//f.h/","/f/h.u//","/f////g.h/","/g//d/","/f/h.g//","/r//g/h","/rest/art/","D/A.R/K/"]
alguritm = choice(algoritm)
if gl == '1':
    print(f'({randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{alguritm}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}/)')
    
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
if gl == '2':
    print(Fore.RED+' pornhub.com')
    print('-----------')
    print(Fore.RED+' sexy.movie.com')
    print('-----------')
    print(Fore.YELLOW+' xnxx.com')
    print('-----------')
    print(Fore.YELLOW+' xxx.com')
    print('-----------')
    print(Fore.RED+' brazz.com')
    print('-----------')
    print(Fore.YELLOW+' siet sex ^')
    print('-----------')
    print(Fore.YELLOW+' https://www.uplooder.net/img/image/10/c0e1a69819a1b987b6d1b63999160b1e/IMG-20230517-232431-364.jpg')
    print('-----------')
    print(Fore.RED+' https://www.uplooder.net/img/image/13/2fef1e02344d8dba30fc07e5fcbbf86b/IMG-20230517-232425-103.jpg')
    print('-----------')
    print(Fore.RED+' https://www.uplooder.net/img/image/45/7aa3c4d6a5d5b09a0b4942b08effd0b6/IMG-20230517-232423-114.jpg')
    print('-----------')
    print(Fore.RED+'https://www.uplooder.net/img/image/37/da14c42ed7020c764c85f1698230c1f8/Screenshot-۲۰۲۳-۰۴-۱۰-۱۰-۲۶-۳۱-۶۰۰-app.lightgram.telem.jpg')
    print('-----------')
    print(Fore.RED+' https://www.uplooder.net/img/image/72/5602e503dce06a8c81780663e66ac3d7/Screenshot-۲۰۲۳-۰۴-۱۰-۱۰-۲۶-۳۱-۶۰۰-app.lightgram.telem.jpg')
    print('-----------')
    print(Fore.RED+' https://s6.uupload.ir/files/e882f8966b6635e29d8ca4aa1e1d5b69.1_5ujw.jpg')
    print('-----------')
    print(Fore.RED+' https://s2.uupload.ir/files/inshot_20230131_145402904_rerk.jpg')
    print('-----------')
    print(Fore.RED+' Link sex ∆')
    print('-----------')
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
    
if gl == '3':
    print(Fore.YELLOW+''' new terminal code 
    pkg install tor
    tor''')
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
    
if gl == '4':
	print(Fore.RED+' http://dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/')
	print('-----------')
	print(Fore.YELLOW+'http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion/')
	print('-----------')
	print(Fore.RED+' http://cathug2kyi4ilneggumrenayhuhsvrgn6qv2y47bgeet42iivkpynqad.onion/')
	print('-----------')
	print(Fore.YELLOW+'http://2ogmrlfzdthnwkez.onion/')
	print('-----------')
	print(Fore.BLUE+' http://gstrewrjhpik7goa.onion/')
	print('-----------')
	print(Fore.BLUE+' http://2kka4f23pcxgqkpv.onion')
	print('-----------')
	print(Fore.YELLOW+'http://zxjfjm5iinmgezyj.onion/')
	print('-----------')
	print(Fore.RED+' http://wk3mtlvp2ej64nuytqm3mjrm6gpulix623abum6ewp64444oreysz7qd.onion/')
	print('-----------')
	print(Fore.RED+' https://doi.org/10.1093/:oso/darksex-darkhack-darkviers.org')
	print('-----------')
	print(Fore.RED+' https://darkweblive.net/ancient-genes-from-neanderthals-can-lead-to-slow-drug-metabolism/')
	print('-----------')
	print(Fore.GREEN+' https://fedscoop.com/gao-bought-guns-dark-web-just-see-easy/')
	print('-----------')
	print(Fore.GREEN+' https://www.neweurope.eu/article/guns-the-dark-web-and-europe/')
	print('-----------')
	print(Fore.GREEN+' https://www.researchgate.net/figure/Screenshot-of-the-shop-page-for-lucky-47_fig2_332099394')
	print('-----------')
	print(Fore.GREEN+' https://landmarkrecovery.com/dark-web-drugs-the-basics/')
	print('-----------')
	print(Fore.GREEN+' https://newsinteractives.cbc.ca/longform/the-new-frontier-of-the-drug-trade')
	print('-----------')
	print(Fore.GREEN+' https://www.renaissancerecovery.com/dark-web-drug-addiction/')
	print('-----------')
	print(Fore.GREEN+' https://www.congress.gov/event/115th-congress/joint-event/LC57781/text?s=1&r=9')
	print('-----------')
	print(Fore.GREEN+' https://darknetdiaries.com/transcript/58/')
	print('-----------')
	print(Fore.GREEN+' https://datac.ca/the-dark-web-drug-trade/')
	print('-----------')
	print(Fore.GREEN+' https://www.anu.edu.au/news/all-news/glock-ghost-guns-up-for-grabs-on-the-dark-web')
	print('-----------')
	print(Fore.GREEN+'https://www-cambridgeindependent-co-uk.cdn.ampproject.org/v/s/www.cambridgeindependent.co.uk/news/amp/buying-guns-and-drugs-on-the-dark-web-is-as-easy-as-buying-on-ebay-finds-rand-europe-9050144/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844125748482&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.cambridgeindependent.co.uk%2Fnews%2Fbuying-guns-and-drugs-on-the-dark-web-is-as-easy-as-buying-on-ebay-finds-rand-europe-9050144%2F ')
	print('-----------')
	print(Fore.GREEN+' https://www.futurity.org/guns-dark-web-2044652/')
	print('-----------')
	print(Fore.GREEN+' https://cosmosmagazine.com/people/society/dark-web-weapons-trade-could-grow-travel-and-change-very-quickly/')
	print('-----------')
	print(Fore.GREEN+' https://www-business--standard-com.cdn.ampproject.org/v/s/www.business-standard.com/amp/article/pti-stories/illegal-weapons-trade-flourishing-on-dark-web-study-119042100199_1.html?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844125748482&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.GREEN+' https://amp-cnn-com.cdn.ampproject.org/v/s/amp.cnn.com/cnn/2016/08/10/us/declassified-illegal-online-weapons-trade/index.html?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844125748482&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.cnn.com%2F2016%2F08%2F10%2Fus%2Fdeclassified-illegal-online-weapons-trade%2Findex.html')
	print('-----------')
	print(Fore.GREEN+' https://www-bbc-com.cdn.ampproject.org/v/s/www.bbc.com/news/world-62983444.amp?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844125748482&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.GREEN+' https://www.prospectmagazine.co.uk/politics/44743/connect-buy-now-fire-how-the-dark-web-allows-criminals-to-buy-weaponsanonymously')
	print('-----------')
	print(Fore.GREEN+' https://www.nytimes.com/2020/03/04/technology/can-you-hire-a-hit-man-online.html')
	print('-----------')
	print(Fore.GREEN+' https://www.channel4.com/programmes/how-to-hire-a-hitman')
	print('-----------')
	print(Fore.GREEN+' https://www.iris.co.uk/webinar/how-to-hire-a-hitman-on-the-dark-web/')
	print('-----------')
	print(Fore.GREEN+' https://www.hackread.com/doctor-bitcoin-dark-web-hitman/')
	print('-----------')
	print(Fore.GREEN+' https://www.forbes.com/sites/thomasbrewster/2021/08/27/dark-web-hitman-scammer-became-an-fbi-informant/?sh=783e945b35ab')
	print('-----------')
	print(Fore.GREEN+' https://www-mirror-co-uk.cdn.ampproject.org/v/s/www.mirror.co.uk/news/uk-news/moment-mum-arrested-trying-hire-29173899.amp?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844124530365&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.mirror.co.uk%2Fnews%2Fuk-news%2Fmoment-mum-arrested-trying-hire-29173899')
	print('-----------')
	print(Fore.GREEN+' https://darkwebhacker.com/')
	print('-----------')
	print(Fore.GREEN+' https://www.gettyimages.com/photos/dark-web-hacker')
	print('-----------')
	print(Fore.GREEN+' https://blockpit.io/unchained/en/why-do-hackers-on-the-dark-web-steal-crypto/')
	print('-----------')
	print(Fore.GREEN+' https://www-cbsnews-com.cdn.ampproject.org/v/s/www.cbsnews.com/amp/minnesota/news/hackers-post-more-stolen-minneapolis-public-school-data-to-dark-web/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.cbsnews.com%2Fminnesota%2Fnews%2Fhackers-post-more-stolen-minneapolis-public-school-data-to-dark-web%2F')
	print('-----------')
	print(Fore.GREEN+' https://www.medpagetoday.com/special-reports/features/103513')
	print('-----------')
	print(Fore.GREEN+' https://portswigger.net/daily-swig/dark-web')
	print('-----------')
	print(Fore.GREEN+' https://onlinedegrees.und.edu/blog/understanding-the-dark-web/')
	print('-----------')
	print(Fore.GREEN+' https://stock.adobe.com/images/darkweb-darknet-and-hacking-concept-hacker-with-cellphone-man-using-dark-web-with-smartphone-mobile-phone-fraud-online-scam-and-cyber-security-threat-scammer-using-stolen-cell-ar-data-code/289481949')
	print('-----------')
	print(Fore.GREEN+' https://www.istockphoto.com/photos/dark-web-hacker')
	print('-----------')
	print(Fore.GREEN+' https://www-dailymail-co-uk.cdn.ampproject.org/v/s/www.dailymail.co.uk/sciencetech/article-11982783/amp/I-hacker-30-years-scariest-things-saw-dark-web.html?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.GREEN+' https://www.shutterstock.com/search/dark-web-hacker')
	print('-----------')
	print(Fore.GREEN+' https://m.facebook.com/4WhiteHats/')
	print('-----------')
	print(Fore.GREEN+' https://virtualizationreview.com/articles/2023/03/14/chatgpt-dark-web.aspx?m=1')
	print('-----------')
	print(Fore.GREEN+' https://darknetdiaries.com/')
	print('-----------')
	print(Fore.GREEN+' https://www.kaspersky.com/resource-center/threats/deep-web')
	print('-----------')
	print(Fore.GREEN+' https://www-govtech-com.cdn.ampproject.org/v/s/www.govtech.com/security/hackers-post-data-to-dark-web-after-massachusetts-cyber-attack?amp_js_v=a6&amp_gsa=1&_amp=true&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.govtech.com%2Fsecurity%2Fhackers-post-data-to-dark-web-after-massachusetts-cyber-attack')
	print('-----------')
	print(Fore.GREEN+' https://www-bleepingcomputer-com.cdn.ampproject.org/v/s/www.bleepingcomputer.com/news/security/cybercrime-job-ads-on-the-dark-web-pay-up-to-20k-per-month/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.bleepingcomputer.com%2Fnews%2Fsecurity%2Fcybercrime-job-ads-on-the-dark-web-pay-up-to-20k-per-month%2F')
	print('-----------')
	print(Fore.GREEN+' https://www.darknet.org.uk/')
	print('-----------')
	print(Fore.GREEN+' https://www.learningpeople.com/uk/blog/cyber-security/hackers-have-deleted-more-than-6500-sites-from-the-dark-web/')
	print('-----------')
	print(Fore.GREEN+' https://thehackernews.com/search/label/dark%20web?m=1')
	print('-----------')
	print(Fore.GREEN+' https://tribune-com-pk.cdn.ampproject.org/v/s/tribune.com.pk/story/2378694/data-of-all-govt-private-websites-hacked-in-one-year-available-on-dark-web?amp_js_v=a6&amp_gsa=1&amp=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.GREEN+' https://commons.lib.jmu.edu/cgi/viewcontent.cgi?article=1032&context=jmurj')
	print('-----------')
	print(Fore.GREEN+' https://www-cobbtechnologies-com.cdn.ampproject.org/v/s/www.cobbtechnologies.com/blog/why-the-dark-web-isnt-what-you-think-the-hacker-profile?amp_js_v=a6&amp_gsa=1&hs_amp=true&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.GREEN+' https://www-techrepublic-com.cdn.ampproject.org/v/s/www.techrepublic.com/article/what-it-costs-to-hire-a-hacker-on-the-dark-web/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844121342013&csi=1&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.GREEN+' https://www.thetimes.co.uk/article/how-hackers-are-recruiting-on-the-dark-web-mpl2hvsss')
	print('-----------')
	print(Fore.RED+' Link Dark :) ^')
	
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	
if gl == '5':
	print(Fore.RED+' https://iplogger.ru.zip')
	print('-----------')
	print(Fore.YELLOW+' https://bit.ly/3ild93L')
	print('-----------')
	print(Fore.RED+' http://ffmodmenu.page.link/Anti-V')
	print('-----------')
	print(Fore.BLUE+' https://cyberpolice.ir/search?s=https%3A%2F%2Frubika.ir%2FSupportBot/')
	print('-----------')
	print(Fore.YELLOW+' http://data.phishtank.com/data/online-valid.csv')
	print('-----------')
	print(Fore.RED+' https://darkweblive.net/?s=%40Netreport')
	print('-----------')
	print(Fore.BLUE+' https://dl.uploadgram.me/60bdffd3a2be4h')
	print('-----------')
	print(Fore.YELLOW+' www.malwaredomainlist.com/')
	print('-----------')
	print(Fore.YELLOW+' support.clean-mx.de/clean-mx/viruses.php')
	print('-----------')
	print(Fore.YELLOW+' malc0de.com/database/')
	print('-----------')
	print(Fore.YELLOW+' vxvault.net//ViriList.php')
	print('-----------')
	print(Fore.YELLOW+' cybercrime-tracker.net/')
	print('-----------')
	print(Fore.YELLOW+' www.virussamples.com/')
	print('-----------')
	print(Fore.YELLOW+' github.com/ytisf/theZoo')
	print('-----------')
	print(Fore.RED+' https://bit.ly/3fX8ljZ')
	print('-----------')
	print(Fore.RED+' https://iplogger.ru.zip')
	print('-----------')
	print(Fore.RED+' https://2a86-93-114-24-154.ngrok.io')
	print('-----------')
	print(Fore.RED+' https://pypi.org/search/?q=filtering+rubika+')
	print('-----------')
	print(Fore.RED+' https://ninja-ide.org/?s=Admin-Rubika-gifsxs-hack-af-vuirs-hacker-filtering')
	print('-----------')
	print(Fore.RED+' https://www.shutterstock.com/search/bug-sex')
	print('-----------')
	print(Fore.RED+' https://www.reddit.com/r/masseffect/comments/p1dbk0/me2_postgame_sex_scene_black_screen_bug/')
	print('-----------')
	print(Fore.RED+' https://www.shutterstock.com/search/hacker-bug')
	print('-----------')
	print(Fore.RED+' https://bit.ly/3fV728378l')
	print('-----------')
	print(Fore.RED+' https://urlhaus.abuse.ch/browse/')
	print('-----------')
	print(Fore.RED+' https://openphish.com/feed.txt')
	print('-----------')
	print(Fore.RED+' http://vxvault.net/URL_List.php')
	print('-----------')
	print(Fore.RED+'https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt ')
	print('-----------')
	print(Fore.RED+' https://osint.bambenekconsulting.com/feeds/')
	print('-----------')
	print(Fore.RED+' https://botvrij.eu/data/')
	print('-----------')
	print(Fore.RED+' https://zerodot1.gitlab.io/CoinBlockerLists/hosts')
	print('-----------')
	print(Fore.RED+' http://www.urlvir.com/export-hosts/')
	print('-----------')
	print(Fore.RED+' https://secure.dshield.org/feeds/suspiciousdomains_Low.txt')
	print('-----------')
	print(Fore.RED+' https://hosts-file.net/?s=')
	print('-----------')
	print(Fore.RED+' http://cybercrime-tracker.net/')
	print('-----------')
	print(Fore.RED+' https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt')
	print('-----------')
	print(Fore.RED+' https://www.spam404.com/')
	print('-----------')
	print(Fore.RED+' https://twitter.com/James_inthe_box')
	print('-----------')
	print(Fore.RED+' https://twitter.com/mesa_matt/ ')
	print('-----------')
	print(Fore.RED+' https://twitter/sex.com')
	print('-----------')
	print(Fore.RED+' https://twitter.com/malware_traffic/ ')
	print('-----------')
	print(Fore.RED+' https://twitter.com/JCyberSec_')
	print('-----------')
	print(Fore.RED+' https://dfff-5-201-222-209.ngrok.io')
	print('-----------')
	print(Fore.RED+'https://bit.ly/nhwhatschat ')
	print('-----------')
	print(Fore.RED+'http://54flq67kqr5wvjqf.onion/python ')
	print('-----------')
	print(Fore.RED+'https://noobhacktube.com ')
	print('-----------')
	print(Fore.RED+' https://IP:61.19.246.18noobhacktube.com')
	print('-----------')
	print(Fore.RED+' https://life-web0.ga/؟I=GOu79Tj')
	print('-----------')
	print(Fore.RED+' https://7/4/2/4/6/1/6/7/2/7/9/1/9/1/6/3/6/www.visualcapitalist.com/cp/charted-the-dark-web-price-index-2022/1/4/7/901/7/8')
	print('-----------')
	print(Fore.RED+'https://crash-bandicoot.info/enfejar/gambling-site ')
	print('-----------')
	print(Fore.RED+' https://crash-bandicoot.info/enfejar/gambling-site/dark-web')
	print('-----------')
	print(Fore.RED+' https://thenextweb.com/security/2017/03/27/oneplus-3-3t-malicious-charger-hack/#.tnw_fHHwquHT')
	print('-----------')
	print(Fore.RED+' https://www.c4isrnet.com/industry/2018/09/25/why-the-market-for-zero-day-vulnerabilities-on-the-dark-web-is-vanishing/')
	print('-----------')
	
	print(Fore.CYAN+' Virus 👾 ؛) ^')
	print('-----------')
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	
	
if gl == '6':
	print(Fore.RED+' https://dscript.com/yftt12k/yftt-filter-rubika.hackers72748')
	print('-----------')
	print(Fore.RED+' http://dscript-sxs22-87-99-typer-filteri.gigfa.com/dxprit.html')
	print('-----------')
	print(Fore.RED+' https://github.com/dxprit-yftt15k-hacker-in-rubika-sex')
	print('-----------')
	print(Fore.RED+' http://dscript-fish33-29-virus-yftt15k-sxs-hack-filter.gigfa.com/index.html')
	print('-----------')
	print(Fore.RED+' http://dxprit-fil-rubika-sxs-sex-hacker-supportbot.phpnet.us')
	print('-----------')
	print(Fore.RED+' https://github.com/Rubika-hacker/http-dxprit-saleh-king99-55-39-hackers.phpnet.us-dxprit.html')
	print('-----------')
	print(Fore.RED+' http://Dxprit-afi-67-kurd-9999999999-28-hacker.phpnet.us')
	print('-----------')
	print(Fore.YELLOW+'Link XD D script ؟) ↑')
	print('-----------')
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	
if gl == '7':
	print(Fore.BLUE+' .goc')
	print('-----------')
	print(Fore.BLUE+' .onion')
	print('-----------')
	print(Fore.BLUE+' .us')
	print('-----------')
	print(Fore.BLUE+' .html')
	print('-----------')
	print(Fore.BLUE+' .ir')
	print('-----------')
	print(Fore.BLUE+' .com')
	print('-----------')
	print(Fore.BLUE+' .gor')
	print('-----------')
	print(Fore.BLUE+' .in')
	print('-----------')
	print(Fore.RED+' v.2.9.5.yftt15k.in')
	print('-----------')
	print(Fore.RED+' v.2.9.5.yftt18k.in')
	print('-----------')
	print(Fore.RED+' /yftt15k.ir')
	print('-----------')
	print(Fore.RED+' /yftt18k.ir')
	print('-----------')
	print(Fore.RED+' /yftt18k.gor')
	print('-----------')
	print(Fore.RED+' /yftt15k.gor')
	print('-----------')
	print(Fore.RED+' https://doi.org/10.1093/acprof:oso/9780195181104.003.0002')
	print('-----------')
	print(Fore.RED+'https://doi.org/10.301/acprof:oso ')
	print('-----------')
	print(Fore.RED+' https://doi.org/10.1093/acprof:oso/dark.gor')
	print('-----------')
	print(Fore.RED+' domain list ?) ')
	print('-----------')
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	
if gl =='8':
	print(Fore.RED+' https://www.uplooder.net/img/image/40/a1532873378ae96cc101c1128f73b039/IMG-20230516-131535-379.jpg(http://wk3mtlvp2ej64nuytqm3mjrm6gpulix623abum6ewp64444oreysz7qd.onion/=http://zxjfjm5iinmgezyj.onion=http://2kka4f23pcxgqkpv.onion=http://gstrewrjhpik7goa.onion/=http://2ogmrlfzdthnwkez.onion/=http://hqfld5smkr4b4xrjcco7zotvoqhuuoehjdvoin755iytmpk4sm7cbwad.onion/=http://cathug2kyi4ilneggumrenayhuhsvrgn6qv2y47bgeet42iivkpynqad.onion/https://www.instagram.com/p/CPGCg2pBUa_/?utm_medium=copy_link‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏(D/A.R/K)')
	print('-----------')
	print(Fore.RED+' https://s6.uupload.ir/files/e882f8966b6635e29d8ca4aa1e1d5b69.1_5ujw.jpg+https://github.com/ytisf/theZoo*https://life-web0.ga/?l=GOu79Tj/http://3soamencp7cpyozc.onion/http://2kka4f23pcxgqkpv.onion/http://zxjfjm5iinmgezyj.onion/underground.phphttp://2ogmrlfzdthnwkez.onion/http://gstrewrjhpik7goa.onion/http://redroomfing27toi.onionhttp://deeplinkdeatbml7.onionhttps://www.instagram.com/p/CPGCg2pBUa_/?utm_medium=copy_link‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏‎‏(D/A.R/K)')
	print('-----------')
	print(Fore.YELLOW+' bug dark gad !) ↑')
	print('-----------')
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')

if gl == '9':
	print(Fore.CYAN+' https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.instagram.com/officialrezapahlavi/&ved=2ahUKEwjVxtzumP3-AhXThP0HHaADA8kQFnoECA8QAQ&usg=AOvVaw3y10FKQ_ya6F1tvbczkA-1')
	print('-----------')
	print(Fore.CYAN+' https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.instagram.com/bbcpersian/%3Fhl%3Dfa&ved=2ahUKEwid666Mmf3-AhUkQfEDHd-mD54QFnoECBAQAQ&usg=AOvVaw3y4X1CNO10ekQVbJ-OaHvv')
	print('-----------')
	print(Fore.CYAN+' https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.instagram.com/chaghu1/&ved=2ahUKEwiY9s_Omf3-AhUVjaQKHbXbAHoQFnoECAwQAQ&usg=AOvVaw1Eu_eauNPOi2kxtIsCZdVH')
	print('-----------')
	print(Fore.CYAN+' https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.instagram.com/molina.ir/%3Fhl%3Dfa&ved=2ahUKEwiVh4zbmf3-AhWJ-6QKHVIJDssQFnoECAkQAQ&usg=AOvVaw0D6QZaUQfaKDjjm3-bMFm9')
	print('-----------')
	print(Fore.GREEN+' Www.Instagram.com/darkweb')
	print('-----------')
	print(Fore.GREEN+' Www.Instagram.com/drugs.2989')
	print('-----------')
	print(Fore.GREEN+' Www.Instagram.com/sheitan_graphy')
	print('-----------')
	print(Fore.GREEN+' Www.Instagram.com/mahsa.amini6610')
	print('-----------')
	print(Fore.GREEN+' Www.Instagram.com/defae.lion')
	print('-----------')
	print(Fore.GREEN+' https://bakht-org.cdn.ampproject.org/v/s/bakht.org/gambling-website/hazarat-bet/amp/?usqp=mq331AQIUAKwASCAAgM%3D&amp_js_v=a9&amp_gsa=1#referrer=https://www.google.com&csi=0')
	print('-----------')
	print(Fore.YELLOW+' viurs Instagram &) ↑')
	print('-----------')
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	print('-----------')
	print(Fore.RED+' MMD matrix ')
algoritm = ["/y//d/f/","/f/h.j/d/","/d//f/h/","/f//a/y/","e//f.h/","/fg.//y/","/f////g.h/","/g//d/","/f/h.g//","/r//g/h","s/e.x//","D/A.R/K/"]
alguritm = choice(algoritm)
if gl == '10':
    print(f'({randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{alguritm}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)})/')
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
    
algoritm = ["/y//d/f/","/f/h.j/d/","/d//f/h/","/f//a/y/","e/h//f.h/","/fg.//y/","/f/u/g.h/","/g//d/","/f/h.g//","/r/f.i/g/h","s/e.x//","D/A.R/K/"]
alguritm = choice(algoritm)
if gl == '11':
    print(f'({randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{alguritm}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}/*)')
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
    
if gl == '12':
    print(Fore.YELLOW+'(0.4.6.10-4) ')
    print('-----------')
    print(Fore.YELLOW+'1.0.3-5 ')
    print('-----------')
    print(Fore.YELLOW+'(0.3-2) ')
    print('-----------')
    print(Fore.YELLOW+' (0.42.2)')
    print('-----------')
    print(Fore.YELLOW+' (3.5.0)')
    print('-----------')
    print(Fore.YELLOW+'(1.1.4) ')
    print('-----------')
    print(Fore.YELLOW+'(0.4.7.11) ')
    print('-----------')
    print(Fore.YELLOW+'(1.6.39) ')
    print('-----------')
    print(Fore.YELLOW+'(1.8.2) ')
    print('-----------')
    print(Fore.YELLOW+'(1.0.9) ')
    print('-----------')
    print(Fore.YELLOW+'(1.3.14-2) ')
    print('-----------')
    print(Fore.YELLOW+' (2.37-8) ')
    print('-----------')
    print(Fore.YELLOW+'(1.0.10) ')
    print('-----------')
    print(Fore.YELLOW+'(1.0.12) ')
    print('-----------')
    print(Fore.YELLOW+' (1.0.0)')
    print('-----------')
    print(Fore.YELLOW+'(2.1.4) ')
    print('-----------')
    print(Fore.YELLOW+' (2.1.12-2)')
    print('-----------')
    print(Fore.YELLOW+'(3.5-4) ')
    print('-----------')
    print(Fore.YELLOW+'(0.5.1) ')
    print('-----------')
    print(Fore.YELLOW+' (1.3.5)')
    print('-----------')
    print(Fore.YELLOW+'(2.10-3) ')
    print('-----------')
    print(Fore.YELLOW+'(2.5.0) ')
    print('-----------')
    print(Fore.YELLOW+'(1.0.9-1) ')
    print('-----------')
    print(Fore.YELLOW+'(2.14.1) ')
    print('-----------')
    print(Fore.YELLOW+'(5.3.1-2) ')
    print('-----------')
    print(Fore.YELLOW+'(0.9.11) ')
    print('-----------')
    print(Fore.YELLOW+'(4.4.0) ')
    print('-----------')
    print(Fore.YELLOW+'(0.7.0-1) ')
    print('-----------')
    print(Fore.YELLOW+'(1.14.0) ')
    print('-----------')
    print(Fore.YELLOW+'(0.4.7.11) ')
    print('-----------')
    print(Fore.YELLOW+'(2.3.7) ')
    print('-----------')
    print(Fore.YELLOW+'(2.42.10) ')
    print('-----------')
    print(Fore.YELLOW+'(1.2.4) ')
    print('-----------')
    print(Fore.YELLOW+'(1.17.6) ')
    print('-----------')
    print(Fore.YELLOW+'(1.50.12) ')
    print('-----------')
    print(Fore.YELLOW+'(2.55.1-2) ')
    print('-----------')
    print(Fore.YELLOW+'(1.9.1-2) ')
    print('-----------')
    print(Fore.YELLOW+'(78.157.38.198) ')
    print('-----------')
    print(Fore.YELLOW+'(194.41.49.18) ')
    print('-----------')  
    print(Fore.YELLOW+'(89.221.81.68) ')
    print('-----------')
    print(Fore.YELLOW+'(194.41.49.12) ')
    print('-----------')
    print(Fore.YELLOW+'(5.160.10.201) ')
    print('-----------')
    print(Fore.YELLOW+'(87.107.133.72) ')
    print('-----------')
    print(Fore.YELLOW+' (185.78.20.130) ')
    print('-----------')
    print(Fore.YELLOW+' (185.143.233.107) ')
    print('-----------')
    print(Fore.YELLOW+' (5.9.152.28) ')
    print('-----------')
    print(Fore.YELLOW+' (185.12.101.54) ')
    print('-----------')
    print(Fore.YELLOW+' (185.12.101.54) ')
    print('-----------')
    print(Fore.YELLOW+' (34.215.241.206)')
    print('-----------')
    print(Fore.YELLOW+' (10.10.34.36)')
    print('-----------')
    print(Fore.YELLOW+' (185.53.178.114)')
    print('-----------')
    print(Fore.YELLOW+' (12.8-p.9)')
    print('-----------')
    print(Fore.YELLOW+' mhkzn tor +) ^ ')
   
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
   
if gl =='13':
	print(Fore.RED+' https://uupload.ir/view/1.1.1.1)2.3.6.5.4.3.2.1.1.2.3.4.5.6.7.h.e-3.2(fil)_st4o.mp4 ')
	print('-----------')
	print(Fore.RED+' https://uupload.ir/view/sexy.movie(filter.rubika)_exae.mp4')
	print('-----------')
	print(Fore.RED+' https://sdaqyi.cn/sucai/zhuanai/zsdt.js')
	print('-----------')
	print(Fore.MAGENTA+' https://s8.uupload.ir/files.dark-sexbug-af/img_20230518_170211_311_s4b9.jpg')
	print('-----------')
	print(Fore.MAGENTA+' https://s8.uupload.ir/files/img_20230518_-fa-fi-dark-hack-gif-sex-afsystem170214_352_j30h.jpg')
	print('-----------')
	print(Fore.YELLOW+' list sex $) ^ ')
	
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
algoritm = ["/y//d/f/","/f/h.j/d/","/d//f/h/","/f//a/y/","e/h//f.h/","/fg.//y/","/f/u/g.h/","/g/i.g/d/","/f/h.g//","/r/f.i/g/h","s/e.x//","D/A.R/K/","/f//Ru./y"]
alguritm = choice(algoritm)
if gl == '14':
    print(f'({randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{alguritm}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}.{randint(1,9)}/*)')
    
    print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
    
if gl == '15':
	print(Fore.WHITE+' https://thesatanictemple.com/')
	print('-----------')
	print(Fore.WHITE+' https://www-churchofsatan-com.cdn.ampproject.org/v/s/www.churchofsatan.com/?amp_js_v=a6&amp_gsa=1&amp&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844115506844&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.churchofsatan.com%2F')
	print('-----------')
	print(Fore.WHITE+' https://www.ojp.gov/ncjrs/virtual-library/abstracts/satan-wants-you-cult-devil-worship-america')
	print('-----------')
	print(Fore.WHITE+' https://www.britannica.com/topic/Church-of-Satan')
	print('-----------')
	print(Fore.WHITE+' https://www.ojp.gov/ncjrs/virtual-library/abstracts/satanic-beliefs-criminal-actions')
	print('-----------')
	print(Fore.WHITE+' https://www.history.com/topics/religion/satanism')
	print('-----------')
	print(Fore.WHITE+' https://www.magnetreleasing.com/satanic/')
	print('-----------')
	print(Fore.WHITE+' http://www.hailsatanfilm.com/')
	print('-----------')
	print(Fore.WHITE+' https://m.soundcloud.com/satan666')
	print('-----------')
	print(Fore.WHITE+' https://www.ncbi.nlm.nih.gov/books/NBK458777/')
	print('-----------')
	print(Fore.WHITE+' https://www.cbc.ca/mediacentre/program/uncover-satanic-panic')
	print('-----------')
	print(Fore.WHITE+' https://amp-abc-net-au.cdn.ampproject.org/v/s/amp.abc.net.au/article/101591462?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844117242859&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Famp.abc.net.au%2Farticle%2F101591462%23aoh%3D16844117242859%26referrer%3Dhttps%253A%252F%252Fwww.google.com%26amp_tf%3D%25D8%25A7%25D8%25B2%2520%25251%2524s')
	print('-----------')
	print(Fore.WHITE+' https://www-abc27-com.cdn.ampproject.org/v/s/www.abc27.com/local-news/york/satanic-temple-preparing-lawsuit-against-york-school-district-that-denied-after-school-program/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844117242859&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.abc27.com%2Flocal-news%2Fyork%2Fsatanic-temple-preparing-lawsuit-against-york-school-district-that-denied-after-school-program%2F')
	print('-----------')
	print(Fore.WHITE+' https://www-syfy-com.cdn.ampproject.org/v/s/www.syfy.com/syfy-wire/satanic-temple-officially-recognized-church?amp_js_v=a6&amp_gsa=1&amp&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844117242859&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fwww.syfy.com%2Fsyfy-wire%2Fsatanic-temple-officially-recognized-church%3Famp%23aoh%3D16844117242859%26referrer%3Dhttps%253A%252F%252Fwww.google.com%26amp_tf%3D%25D8%25A7%25D8%25B2%2520%25251%2524s')
	print('-----------')
	print(Fore.WHITE+' https://thehill-com.cdn.ampproject.org/v/s/thehill.com/homenews/3662156-satanic-temple-suing-indiana-over-states-near-total-abortion-ban/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844117242859&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s')
	print('-----------')
	print(Fore.WHITE+' https://theworld.org/stories/2019-05-06/satanic-temple-gets-religious')
	print('-----------')
	print(Fore.WHITE+' https://globalnews-ca.cdn.ampproject.org/v/s/globalnews.ca/news/5488632/satanic-temple-canada/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQIUAKwASCAAgM%3D#aoh=16844117242859&referrer=https%3A%2F%2Fwww.google.com&amp_tf=%D8%A7%D8%B2%20%251%24s&ampshare=https%3A%2F%2Fglobalnews.ca%2Fnews%2F5488632%2Fsatanic-temple-canada%2F')
	print('-----------')
	print(Fore.WHITE+' https://www.americansatanmovie.com/')
	print('-----------')
	print(Fore.WHITE+' https://thesatanictempleminnesota.com/')
	print('-----------')
	print('-----------')
	print(Fore.WHITE+' https://thesatanictempleminnesota.com/')
	print('-----------')
	
	
	print(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	
		
	(Fore.RED+'  end of work   Author: HACKER JAHANAMI     Manufacturer: HACKER JAHANAMI')
	
		
	
